language: cpp
sudo: required
dist: trusty
os: linux
compiler: gcc

branch:
    only:
        - master

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install libsdl2-2.0 libsdl2-dev libboost-all-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j6
    - make test
