language: cpp
sudo: false
dist: trusty
os: linux

compiler:
    - gcc
    - clang

env:
    - BUILD_TYPE=Debug VERBOSE=1
    - BUILD_TYPE=Release VERBOSE=1

install:
    sudo apt-get install libgles2-mesa-dev libegl1-mesa-dev libsdl2-dev libboost-all-dev

script: ./build.sh

notifications:
    email: false
